array:
	gcc ./Arrays/arrays.cpp -o arrays 
	./arrays  

graphs:
	gcc ./Graphs/graphs.cpp -o graphs
	./graphs

hashing:
	gcc ./Hashing/hashing.cpp -o hashing
	./hashing

linkedlist:
	gcc ./LinkedList/linkedList.cpp -o linkedlist
	./linkedlist

queue:
	gcc ./Queue/queue.cpp -o queue
	./queue

stacks:
	gcc ./Stacks/stacks.cpp -o stacks
	./stacks

trees:
	gcc ./Trees/trees.cpp -o trees
	./trees


